# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robot_arm_controller
    - gripper_controller

  robot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  gripper_controller:
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - panda_finger_joint1
      - panda_finger_joint2